[package]
name = "dinai"
version = "0.1.0"
authors = ["Miloslav Smicik", "Peter Strycek"]
edition = "2018"

[dependencies]
rand = "0.7.3"
rand_distr = "0.3.0"

[dependencies.sdl2]
version = "0.34"
default-features = false
features = ["ttf"]
